apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  ports:
    - port: 7077
      name: spark-master
    - port: 8080
      name: spark-ui
  selector:
    app: spark
    role: master
  clusterIP: None