apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  ports:
  - port: 8080
    name: spark-worker-ui
  selector:
    app: spark
    role: worker
  clusterIP: None