apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    service: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      hostname: zookeeper
      restartPolicy: Always
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.2
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_DATA_DIR
          value: "/var/lib/zookeeper/data"
        - name: ZOOKEEPER_LOG_DIR
          value: "/var/lib/zookeeper/log"
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: zookeeper-data
          - mountPath: /var/lib/zookeeper/log
            name: zookeeper-log
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: zookeeper-log
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi