apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  clusterIP: None
  selector:
    service: kafka
  ports:
    - name: internal
      port: 29092 # port specifies the Service listening port for incoming traffi
      targetPort: 29092 #  specifies the port number for routing traffic to the Service‘s pods (internal communication)
    - name: external
      port: 30092
      targetPort: 9092